export const env = {
  NEXT_PUBLIC_SANITY_PROJECT_ID: process.env
    .NEXT_PUBLIC_SANITY_PROJECT_ID as string,
  NEXT_PUBLIC_SANITY_DATASET: process.env.NEXT_PUBLIC_SANITY_DATASET as string,
  NEXT_PUBLIC_SANITY_API_VERSION: process.env
    .NEXT_PUBLIC_SANITY_API_VERSION as string,
}
