/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CreditGroup = {
  _id: string;
  _type: "creditGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  order?: number;
  entries?: Array<{
    name?: string;
    instagram?: string;
    _type: "creditEntry";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  stageName?: string;
  role?:
    | "model"
    | "production"
    | "photographer"
    | "volunteer"
    | "institutional"
    | "partner";
  instagram?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  fullName?: string;
  segment?: string;
  instagram?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type Look = {
  _id: string;
  _type: "look";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lookNumber?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    photographerName?: string;
    photographerInstagram?: string;
    _type: "image";
    _key: string;
  }>;
  model?: {
    name?: string;
    instagram?: string;
  };
  styling?: Array<string>;
};

export type NextEvent = {
  _id: string;
  _type: "nextEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  edition?: string;
  date?: string;
  location?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  edition?: string;
  humanDate?: string;
  displayDate?: string;
  isoDate?: string;
  location?: string;
  concept?: string;
  intro?: string;
  longDescription?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | CreditGroup
  | SanityImageAssetReference
  | Person
  | SanityImageCrop
  | SanityImageHotspot
  | Brand
  | Look
  | NextEvent
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/queries/brands.ts
// Variable: allBrandsQuery
// Query: *[_type == "brand"] | order(name asc) {    _id,    name,    fullName,    segment,    instagram,    image  }
export type AllBrandsQueryResult = Array<{
  _id: string;
  name: string | null;
  fullName: string | null;
  segment: string | null;
  instagram: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries/credits.ts
// Variable: allCreditGroupsQuery
// Query: *[_type == "creditGroup"] | order(order asc) {    _id,    title,    entries[] {      _key,      name,      instagram    }  }
export type AllCreditGroupsQueryResult = Array<{
  _id: string;
  title: string | null;
  entries: Array<{
    _key: string;
    name: string | null;
    instagram: string | null;
  }> | null;
}>;

// Source: src/sanity/queries/event.ts
// Variable: currentEventQuery
// Query: *[_type == "event"] | order(_createdAt asc) [0] {    name,    edition,    humanDate,    displayDate,    isoDate,    location,    concept,    intro,    longDescription  }
export type CurrentEventQueryResult = {
  name: string | null;
  edition: string | null;
  humanDate: string | null;
  displayDate: string | null;
  isoDate: string | null;
  location: string | null;
  concept: string | null;
  intro: string | null;
  longDescription: string | null;
} | null;

// Source: src/sanity/queries/event.ts
// Variable: nextEventQuery
// Query: *[_type == "nextEvent"] | order(_createdAt asc) [0] {    edition,    date,    location  }
export type NextEventQueryResult = {
  edition: string | null;
  date: string | null;
  location: string | null;
} | null;

// Source: src/sanity/queries/looks.ts
// Variable: allLooksQuery
// Query: *[_type == "look"] | order(lookNumber asc) {    _id,    lookNumber,    images[]{      asset,      alt,      photographerName,      photographerInstagram    },    model {      name,      instagram    },    styling  }
export type AllLooksQueryResult = Array<{
  _id: string;
  lookNumber: string | null;
  images: Array<{
    asset: SanityImageAssetReference | null;
    alt: string | null;
    photographerName: string | null;
    photographerInstagram: string | null;
  }> | null;
  model: {
    name: string | null;
    instagram: string | null;
  } | null;
  styling: Array<string> | null;
}>;

// Source: src/sanity/queries/people.ts
// Variable: allModelsQuery
// Query: *[_type == "person" && role == "model"] | order(order asc, stageName asc) {    _id,    name,    stageName,    instagram,    image  }
export type AllModelsQueryResult = Array<{
  _id: string;
  name: string | null;
  stageName: string | null;
  instagram: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries/people.ts
// Variable: executiveProducerQuery
// Query: *[_type == "person" && role == "production"] | order(order asc) [0] {    _id,    name,    stageName,    instagram,    image  }
export type ExecutiveProducerQueryResult = {
  _id: string;
  name: string | null;
  stageName: string | null;
  instagram: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "brand"] | order(name asc) {\n    _id,\n    name,\n    fullName,\n    segment,\n    instagram,\n    image\n  }\n': AllBrandsQueryResult;
    '\n  *[_type == "creditGroup"] | order(order asc) {\n    _id,\n    title,\n    entries[] {\n      _key,\n      name,\n      instagram\n    }\n  }\n': AllCreditGroupsQueryResult;
    '\n  *[_type == "event"] | order(_createdAt asc) [0] {\n    name,\n    edition,\n    humanDate,\n    displayDate,\n    isoDate,\n    location,\n    concept,\n    intro,\n    longDescription\n  }\n': CurrentEventQueryResult;
    '\n  *[_type == "nextEvent"] | order(_createdAt asc) [0] {\n    edition,\n    date,\n    location\n  }\n': NextEventQueryResult;
    '\n  *[_type == "look"] | order(lookNumber asc) {\n    _id,\n    lookNumber,\n    images[]{\n      asset,\n      alt,\n      photographerName,\n      photographerInstagram\n    },\n    model {\n      name,\n      instagram\n    },\n    styling\n  }\n': AllLooksQueryResult;
    '\n  *[_type == "person" && role == "model"] | order(order asc, stageName asc) {\n    _id,\n    name,\n    stageName,\n    instagram,\n    image\n  }\n': AllModelsQueryResult;
    '\n  *[_type == "person" && role == "production"] | order(order asc) [0] {\n    _id,\n    name,\n    stageName,\n    instagram,\n    image\n  }\n': ExecutiveProducerQueryResult;
  }
}
